services:
  - type: web
    name: node-red
    plan: free
    region: frankfurt
    env: node
    repo: https://github.com/lebalz/node-red-render.git
    buildCommand: npm install
    startCommand: node --max-old-space-size=480 node_modules/node-red/red.js --settings ./settings.js
    healthCheckPath: /
    envVars:
      - key: NODE_RED_USERNAME
        description: the username to secure the editor with, default[admin]
        sync: false
      - key: NODE_RED_PASSWORD
        description: the password to secure the editor with, default[password]
        sync: false
      - key: DATABASE_URL
        value: ""  # Jika kosong, maka pgutil tidak akan menginisialisasi PostgreSQL

# Catatan:
# Bagian `databases:` bisa dihapus jika tidak digunakan lagi.
